### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by bararchy** [t-richards/vulnsearch#1]
Hi,
Nice project :) 
As this is a standalone program and not a "real" shard, would you consider to add a Makefile ? so a clone & make will work ?

**Comment by t-richards** [comment]
I will certainly consider it. :smile: 

For ease-of-use, there should definitely be a build tool. Is GNU Make the usual choice for Crystal projects? I'm not opposed to it at all. I am, however, wondering if there's a more "Crystal" way of which I am not aware.
